server:
  port: 8763 # Indicate the default PORT where this service will be started

eureka:
  instance:
    hostname: localhost
    appname: authentication-service
  client:
    registerWithEureka: true # telling the server not to register himself in the service
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
